name: task_manager_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1


environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_modular: ^6.3.4
  supabase_flutter: ^2.8.4
  cupertino_icons: ^1.0.8
  envied: ^0.3.0
  provider: ^6.1.4
  intl: ^0.20.2
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  sqflite: ^2.0.0
  timezone: ^0.9.4
  android_intent_plus: ^5.3.0
  permission_handler: ^11.3.1
  workmanager: ^0.5.1
  fl_chart: ^0.71.0
  image_picker: ^1.1.2
  flutter_local_notifications: ^18.0.1
  shimmer: ^3.0.0
  http: ^1.4.0
  path_provider: ^2.1.5
  native_image_cropper: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  envied_generator: ^0.3.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/
