// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-XLn6HdDYGDWMiQRujez8lRxlgz_qecU',
    appId: '1:964523569905:web:082b46b39f984879446f50',
    messagingSenderId: '964523569905',
    projectId: 'taskmanager-d2817',
    authDomain: 'taskmanager-d2817.firebaseapp.com',
    storageBucket: 'taskmanager-d2817.firebasestorage.app',
    measurementId: 'G-Y7J5WLXP97',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJZIIifYzCW4a5gDvEfMLRC1h8-n4qtfA',
    appId: '1:964523569905:android:d343de20b6638bc3446f50',
    messagingSenderId: '964523569905',
    projectId: 'taskmanager-d2817',
    storageBucket: 'taskmanager-d2817.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSkmNPpUQlvc7i0-W0c3xMnDBz_Ng9qWc',
    appId: '1:964523569905:ios:5d061322a94fca21446f50',
    messagingSenderId: '964523569905',
    projectId: 'taskmanager-d2817',
    storageBucket: 'taskmanager-d2817.firebasestorage.app',
    iosBundleId: 'com.example.taskManagerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSkmNPpUQlvc7i0-W0c3xMnDBz_Ng9qWc',
    appId: '1:964523569905:ios:5d061322a94fca21446f50',
    messagingSenderId: '964523569905',
    projectId: 'taskmanager-d2817',
    storageBucket: 'taskmanager-d2817.firebasestorage.app',
    iosBundleId: 'com.example.taskManagerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-XLn6HdDYGDWMiQRujez8lRxlgz_qecU',
    appId: '1:964523569905:web:f29b5bd9fb23c137446f50',
    messagingSenderId: '964523569905',
    projectId: 'taskmanager-d2817',
    authDomain: 'taskmanager-d2817.firebaseapp.com',
    storageBucket: 'taskmanager-d2817.firebasestorage.app',
    measurementId: 'G-YZK60Z08FX',
  );
}
